name: Build Docker Image

on:
  push:
    branches: [master]

env:
  APP_NAME: yesplaymusic
  DOCKERHUB_REPO: dockercommo/yesplaymusic
  # 添加 Yarn 缓存密钥，提高构建速度
  CACHE_KEY: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-{{ env.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          yarn config set strict-ssl false  # 解决证书验证问题
          yarn install
      - name: Build the Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --tag ${{ env.DOCKERHUB_REPO }}:latest \
            --tag ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }} \
            --build-arg APP_NAME=${{ env.APP_NAME }} \
            --build-arg APP_VERSION=${{ env.APP_VERSION }} \
            --cache-from type=local,src=type=registry,ref=${{ env.DOCKERHUB_REPO }}:latest \
            -f Dockerfile .
